---
- name: Установка стандартных пакетов
  hosts: all
  roles:
    - role: default_packages
  tags:
    - install_packages

- name: Уставнока и настройка nginx для проксирования
  hosts: proxy
  roles:
    - role: nginx_proxy
  tags:
    - nginx_proxy

- name: Установка и настройка nginx c кастомной страницей
  hosts: nginx
  roles:
    - role: nginx_custom
  tags:
    - nginx_custom
